"""
===============================================================================
 PHC-PULSE - BACKEND API (STUB VERSION)
===============================================================================

WHAT THIS FILE DOES
-------------------
A Flask web server exposing three GET endpoints that the frontend will call:

    GET /forecast/<phc_id>        -> 7-day demand forecast (stub)
    GET /alert/<phc_id>           -> stock-out alert status   (stub)
    GET /redistribution-plan      -> transfer recommendations (stub)

THE STUB-FIRST STRATEGY
-----------------------
The functions get_forecast / get_alert / get_redistribution_plan currently
return realistic DUMMY data. This lets the frontend be built and tested
today, without waiting for the ML model or the optimizer. Later, each stub
gets replaced by the real thing in ONE place, and the frontend changes not
at all:

    get_forecast            -> train_forecast_model.predict_demand()
    get_alert               -> alert_engine.check_alert()
    get_redistribution_plan -> redistribution.solve_redistribution()

CORS
----
flask-cors is enabled for everything, so a frontend served from a different
local port (e.g. Live Server on 5500) can call this API without the browser
blocking it.

HOW TO RUN
----------
    pip install flask flask-cors   (inside your venv, once)
    python app.py
Then open in a browser:  http://127.0.0.1:5000/forecast/PHC_01
===============================================================================
"""

from flask import Flask, jsonify, abort
from flask_cors import CORS


# =============================================================================
# SECTION 1: APP SETUP
# =============================================================================

app = Flask(__name__)
CORS(app)   # allow cross-origin requests from the frontend's port

# The valid PHC ids, exactly as generated by generate_phc_data.py
# (5 districts x 4 PHCs = PHC_01 ... PHC_20).
VALID_PHCS = [f"PHC_{i:02d}" for i in range(1, 21)]


# =============================================================================
# SECTION 2: STUB FUNCTIONS (swap these for the real ones later)
# =============================================================================

def get_forecast(phc_id):
    """STUB: later -> predict_demand(phc_id, drug, recent_data) from the model."""
    return {
        "phc_id": phc_id,
        "drug_name": "antimalarial",
        "forecast_7day": [32, 34, 33, 36, 38, 40, 42],
    }


def get_alert(phc_id):
    """STUB: later -> check_alert(...) from alert_engine.py."""
    return {
        "phc_id": phc_id,
        "drug_name": "antimalarial",
        "status": "CRITICAL",
        "days_remaining": 3.2,
        "message": (f"antimalarial at {phc_id} will last approximately 3.2 "
                    f"more days; lead time is 7 days - reorder now."),
    }


def get_redistribution_plan():
    """STUB: later -> solve_redistribution(...) from redistribution.py."""
    return [
        {"from": "PHC_1", "to": "PHC_2", "quantity": 50, "drug_name": "antimalarial"},
        {"from": "PHC_3", "to": "PHC_2", "quantity": 30, "drug_name": "antimalarial"},
        {"from": "PHC_4", "to": "PHC_5", "quantity": 20, "drug_name": "respiratory"},
    ]


# =============================================================================
# SECTION 3: ROUTES (the URLs the frontend calls)
# =============================================================================

@app.route("/forecast/<phc_id>", methods=["GET"])
def forecast(phc_id):
    if phc_id not in VALID_PHCS:
        abort(404)                      # unknown PHC -> JSON error below
    return jsonify(get_forecast(phc_id))


@app.route("/alert/<phc_id>", methods=["GET"])
def alert(phc_id):
    if phc_id not in VALID_PHCS:
        abort(404)
    return jsonify(get_alert(phc_id))


@app.route("/redistribution-plan", methods=["GET"])
def redistribution_plan():
    return jsonify(get_redistribution_plan())


# =============================================================================
# SECTION 4: ERROR HANDLERS
# By default Flask returns ugly HTML errors. We replace 404 (and 500) with
# clean JSON so the frontend can display them properly.
# =============================================================================

@app.errorhandler(404)
def not_found(error):
    return jsonify({
        "error": "Not found",
        "message": ("Unknown PHC id or endpoint. Valid PHC ids are "
                    "PHC_01 through PHC_20."),
    }), 404


@app.errorhandler(500)
def server_error(error):
    return jsonify({"error": "Server error",
                    "message": "Something broke on our side. Try again."}), 500


# =============================================================================
# SECTION 5: START THE SERVER
# debug=True: auto-reloads on save + shows detailed errors (DEV ONLY -
# turn this off for the deployed version).
# =============================================================================

if __name__ == "__main__":
    app.run(debug=True, port=5000)
